logging:
  level:
    org:
      springframework:
        boot: DEBUG

spring:
  application:
    name: gulimall-member

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.80.131:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        application:
          name: gulimall-member
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml

  config:
    import: optional:nacos:gulimall-member.yaml


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
